name: env_sycamore  # Name of your Conda environment

channels:            # Conda channels to search for packages
  - defaults         # Default Conda channel
  - conda-forge     # Conda Forge channel (optional, but often useful for additional packages)

dependencies:
  - numpy
  - tqdm
  - matplotlib
  - pip
  - pandas
  - statsmodels
  - xarray
  - spyder
  - SciPy
  - glimix-core
  - stdpopsim
  - pandas-plink

#create environment: 
#conda env create -f argwas_environment.yml

#activate environment:
#conda activate env_argwas

#install stdpopsim:
#conda install -c conda-forge stdpopsim
#conda install -c conda-forge gsl
#conda install -c conda-forge openblas

#install tsinfer:
#conda install -c conda-forge tsinfer

#install logfile package:
#pip install python_log_indenter

#install egrm:
#cd ~/git/argwas/
#pip install ./egrm

#ignore the error about the numpy version. this has nothing to do with gsl or openblas

# uninstall environment: conda env remove -n env_argwas
#    - numpy>=1.22.3,<1.23.0
#    - gsl=2.2.1
#install plink:
#pip install pandas-plink
